### PR TITLE
Port to 1.16

### PR DESCRIPTION
**Pull request by Bendimester23**
I had to use flat dir for the libraries for now, because i ported Fabric Placeholder Api with the custom text parser to 1.16.

### CODE REVIEW

**Comment by Patbox** [comment]
Could you PR hologram-api itself to repo for it? I will release it as needed.
With Placeholder API, it's better to use stock 0.3.0 (which should be compatible excluding text parser) and include ported TextParser with this repo

**Comment by Patbox** [comment]
Looks good, but it might use client only methods now (as Mojang stopped removing unused ones only with 1.17), so make sure all formatting works!

**Comment by Bendimester23** [comment]
Only gradient seems broken, but it is an easy fix. I will do it an hour later however.

**Comment by Bendimester23** [comment]
kép
Every formatting works now.(The first line was a problem with IntelIJ's terminal input and I forgot to remove it)

**Comment by Patbox** [comment]
Fonts?

**Comment by Bendimester23** [comment]
Oh, I forgot that one. I'll test it now.

**Comment by Bendimester23** [comment]
It crashed, but I fixed it with an accessWidener, now it works in the chat, but not on the hologram itself

**Comment by Bendimester23** [comment]
kép
also somehow text rendering is glitched

**Comment by Patbox** [comment]
Thats not full font file, vanilla issue

**Comment by Bendimester23** [comment]
kép
fixed the problem with a bit of reflection

**Comment by Patbox** [comment]
Well, 1.16 is way little too old now for my interest now

**Pull request closed without merging**
